steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${_IMAGE_VERSION}', '.']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${_IMAGE_VERSION}']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest']
timeout: 900s
substitutions:
  _IMAGE_NAME: "lab-portal"                 # default value
  _IMAGE_VERSION: "0.1"                     # default value
